export const styles = {
  root: { fontFamily: "'Noto Sans JP','Hiragino Kaku Gothic ProN',sans-serif", minHeight: "100vh", background: "#f8f9fb", color: "#1a1a2e" },
  header: { background: "#1a1a2e", color: "white", padding: "16px 24px" },
  headerInner: { maxWidth: 860, margin: "0 auto" },
  logo: { fontSize: 22, fontWeight: 700 },
  subtitle: { fontSize: 12, color: "#a78bfa", marginTop: 2 },
  tabBar: { background: "#1a1a2e", borderBottom: "1px solid #2d2d4e", padding: "0 24px", display: "flex", gap: 4 },
  tab: { padding: "10px 18px", border: "none", cursor: "pointer", fontSize: 13, fontWeight: 500 },
  body: { maxWidth: 860, margin: "0 auto", padding: "20px 16px" },
  card: { background: "white", borderRadius: 12, padding: "16px 18px", marginBottom: 14, boxShadow: "0 1px 4px rgba(0,0,0,.07)" },
  cardTitle: { fontSize: 13, fontWeight: 700, color: "#4b5563", marginBottom: 10 },
  input: { width: "100%", padding: "9px 12px", border: "1.5px solid #e5e7eb", borderRadius: 8, fontSize: 14, outline: "none", background: "white", color: "#1a1a2e", boxSizing: "border-box" },
  label: { display: "block", fontSize: 12, color: "#6b7280", marginBottom: 4 },
  dropdownList: { position: "absolute", zIndex: 999, top: "calc(100% + 4px)", left: 0, right: 0, background: "white", border: "1.5px solid #e5e7eb", borderRadius: 10, maxHeight: 200, overflowY: "auto", boxShadow: "0 8px 24px rgba(0,0,0,.12)" },
  dropdownItem: { padding: "9px 14px", cursor: "pointer", display: "flex", justifyContent: "space-between", alignItems: "center", fontSize: 14 },
  dropdownEmpty: { padding: "12px 14px", color: "#aaa", fontSize: 13 },
  rowLine: { display: "flex", gap: 8, alignItems: "center", marginBottom: 8 },
  selectedMat: { display: "flex", alignItems: "center", gap: 8, background: "#f0f4ff", border: "1.5px solid #c7d2fe", borderRadius: 8, padding: "8px 12px", fontSize: 14 },
  matBadge: { background: "#e0e7ff", color: "#4338ca", borderRadius: 6, padding: "2px 7px", fontSize: 11, fontWeight: 600 },
  clearBtn: { marginLeft: "auto", background: "none", border: "none", cursor: "pointer", color: "#9ca3af", fontSize: 13 },
  removeBtn: { background: "none", border: "none", cursor: "pointer", fontSize: 16, color: "#d1d5db", flexShrink: 0 },
  addRowBtn: { marginTop: 4, background: "none", border: "1.5px dashed #d1d5db", borderRadius: 8, padding: "7px 14px", color: "#9ca3af", cursor: "pointer", fontSize: 13, width: "100%" },
  resultCard: { background: "linear-gradient(135deg,#1a1a2e 0%,#16213e 100%)", color: "white", borderRadius: 14, padding: "20px 22px", boxShadow: "0 4px 20px rgba(26,26,46,.2)" },
  resultTitle: { fontSize: 14, color: "#a78bfa", fontWeight: 600 },
  resultGrid: { display: "grid", gridTemplateColumns: "1fr 1fr 1fr 1fr", gap: 12, marginBottom: 16 },
  resultItem: { background: "rgba(255,255,255,.06)", borderRadius: 10, padding: "12px 14px" },
  resultLabel: { fontSize: 11, color: "#9ca3af", marginBottom: 6 },
  resultValue: { fontSize: 20, fontWeight: 700 },
  suggestBox: { background: "rgba(167,139,250,.15)", border: "1px solid rgba(167,139,250,.4)", borderRadius: 10, padding: "14px 16px" },
  suggestLabel: { fontSize: 12, color: "#c4b5fd", marginBottom: 6 },
  suggestValue: { fontSize: 26, fontWeight: 800, color: "#e8d5ff" },
  suggestSub: { fontSize: 12, fontWeight: 400, color: "#a78bfa", marginLeft: 8 },
  gauge: { height: 10, background: "rgba(255,255,255,.1)", borderRadius: 5, position: "relative" },
  gaugeBar: { height: "100%", borderRadius: 5, transition: "width .5s,background .5s" },
  gaugeTarget: { position: "absolute", top: -3, width: 2, height: 16, background: "#a78bfa", borderRadius: 1, transform: "translateX(-50%)" },
  th: { padding: "8px 10px", fontSize: 12, color: "#6b7280", textAlign: "left", fontWeight: 600 },
  td: { padding: "10px 10px", fontSize: 14 },
  unitBadge: { background: "#f3f4f6", color: "#374151", borderRadius: 6, padding: "2px 8px", fontSize: 12 },
  btnPrimary: { background: "#1a1a2e", color: "white", border: "none", borderRadius: 8, padding: "9px 16px", fontWeight: 600, cursor: "pointer", fontSize: 14 },
  btnSmBlue: { background: "#eff6ff", color: "#1d4ed8", border: "1px solid #bfdbfe", borderRadius: 6, padding: "4px 10px", fontSize: 12, cursor: "pointer", fontWeight: 500 },
  btnSmRed: { background: "#fff1f2", color: "#be123c", border: "1px solid #fecdd3", borderRadius: 6, padding: "4px 10px", fontSize: 12, cursor: "pointer", fontWeight: 500 },
  btnSmGreen: { background: "#f0fdf4", color: "#16a34a", border: "1px solid #bbf7d0", borderRadius: 6, padding: "4px 10px", fontSize: 12, cursor: "pointer", fontWeight: 500 },
  btnSmGray: { background: "#f9fafb", color: "#374151", border: "1px solid #e5e7eb", borderRadius: 6, padding: "4px 10px", fontSize: 12, cursor: "pointer", fontWeight: 500 },
};
